### ISSUE TITLE
CLI Should work on Node 16 and NPM 7/8

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/brightlayer-ui-cli#117]
#### Describe the desired behavior
CLI should work flawlessly with the latest versions of Node and NPM.

#### Describe the current behavior
The CLI works best with Node 14 and NPM 6. It will work with NPM7 if it's globally installed. When using the latest versions, a lot of things seem to be broken.

#### Is this request related to a current issue?
This is related to a number of issues that were identified after trying to update to the latest node.

**Comment by joebochill** [comment]
I'm curious if we can get this to work by listing the underlying CLI packages as dependencies instead of running them via NPX.

**Comment by daileytj** [comment]
We can get by without any cli changes if we let users know to install the respective underlying cli package via the npx `--package` flag.

angular: `npx -p @brightlayer-ui/cli@beta --package=@angular/cli blui new --framework=angular`
react: `npx -p @brightlayer-ui/cli@beta --package=create-react-app blui new --framework=react` 
react: `npx -p @brightlayer-ui/cli@beta --package=react-native blui new --framework=react-native` 

However, the `create-react-app` and `react-native` packages automatically use the latest react version which causes some peer dependency issues with react v18 when generating the project. This requires the end user to downgrade the `react` and `react-dom` dependencies back to `^17.0.0`.

This makes me think, and agree with @joebochill's comment, that we can just add the cli dependencies to our CLI to solve this issue for now. This will need to be optimized in the future because the end-user will be installing all 3 underlying CLI's regardless of which framework they are using for their generated project.
